logging:
  level:
    com:
      ssau:
        chat: trace
    org:
      hibernate:
        SQL: debug
    root: error

spring:
  application:
    name: chat
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

security:
  jwt:
    access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh_token_expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

secure:
  jwt:
    secret_key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: method
  default-produces-media-type: application/json


